Cell Centers and Volumes
Computational-Rheology/CRheoLab pull request #12
Opened 2021-07-14 13:51 UTC by BernardoLFaria

There is a Cell_data.txt where is written the output

2021-07-14 16:38 UTC, brunoramoa requested changes
Did you check if the calculations are correct ?

2021-07-14 16:38 UTC, brunoramoa commented on main.cpp
> +//#include "calCellCentersVols.cpp"
Please remove this line

2021-07-14 16:38 UTC, brunoramoa commented on main.cpp
> -    for (unsigned int i = 0; i< polyMesh.nFaces_ ; i++)
move this from main.cpp to the mesh.cpp

2021-07-14 17:33 UTC, brunoramoa reviewed
Did you verify the calculations?

2021-07-14 22:50 UTC, BernardoLFaria commented
> Did you verify the calculations?
I used checkMesh in OpenFOAM v2012 to get the cellVolumes and gives me this huge difference in terms of volumes. I would be grateful if you could confirm me in OpenFOAM v2106 if the cellVolumes I obtained from v2012 are indeed correct.
![image](https://user-images.githubusercontent.com/85550701/125702148-193ebf09-52ff-4407-8fdf-7cbe9b7babcc.png)

2021-07-15 07:56 UTC, brunoramoa commented
You can obtain the cell centers with:
postProcess -func writeCellCentres

And the cell volumes with:
postProcess -func writeCellVolumes

2021-07-15 13:28 UTC, BernardoLFaria commented
> You can obtain the cell centers with:
> postProcess -func writeCellCentres
> 
> And the cell volumes with:
> postProcess -func writeCellVolumes

I already collected the data, as also put in a SpreadSheet. However, there is the SpreadSheet always return.
![image](https://user-images.githubusercontent.com/85550701/125795466-3025810e-4653-4fad-8e7d-06b980cf7045.png)

I think is due to the way numbers are encoding/format. If you could help , I would be grateful .. I leave the document attached:[myData.ods](https://github.com/Computational-Rheology/CRheoLab/files/6823383/myData.ods) .

2021-07-15 13:35 UTC, BernardoLFaria commented
> > You can obtain the cell centers with:
> > postProcess -func writeCellCentres
> > And the cell volumes with:
> > postProcess -func writeCellVolumes
> 
> I already collected the data, as also put in a SpreadSheet. However, there is the SpreadSheet always return.
> ![image](https://user-images.githubusercontent.com/85550701/125795466-3025810e-4653-4fad-8e7d-06b980cf7045.png)
> 
> I think is due to the way numbers are encoding/format. If you could help , I would be grateful .. I leave the document attached:[myData.ods](https://github.com/Computational-Rheology/CRheoLab/files/6823383/myData.ods) .

I already correct the error . It is the formating of the numbers

2021-07-15 21:02 UTC, closed without merging