Non orthogonality
Computational-Rheology/CRheoLab pull request #22
Opened 2021-11-11 15:48 UTC by iamkundan

Comments and Vector Graphics added by Team 4

2021-11-11 15:59 UTC, brunoramoa requested changes

2021-11-11 15:59 UTC, brunoramoa commented on doc/pages/meshParameters.md
> +S_f = getAreaVector()
Use vector syntax...

2021-11-11 15:59 UTC, brunoramoa commented on doc/pages/meshParameters.md
> +theta = acos(d_n.nf/[|d_n|.|n|])
use latex syntax in here...

2021-11-11 15:59 UTC, brunoramoa commented on doc/Images/nonOnthogonality/fcOT.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Images, must have vector syntax...

2021-11-11 18:38 UTC, iamkundan reviewed
Okay

2021-11-12 10:28 UTC, jayeshgolhar7 commented on doc/Images/nonOnthogonality/fcOT.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Images are changed to vector format.

2021-11-12 10:47 UTC, jayeshgolhar7 commented on doc/pages/meshParameters.md
> +\f$\vec{d}\f$ = Vector from Cell Owner Centre of Mass to Neighbour Cell Centre of Mass
wrote the equations in vector format.

2021-11-12 11:04 UTC, iamkundan commented on doc/pages/meshParameters.md
> +\f$\vec{d}\f$ = Vector from Cell Owner Centre of Mass to Neighbour Cell Centre of Mass
completed

2021-11-12 11:04 UTC, iamkundan commented on doc/Images/nonOnthogonality/fcOT.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
completed

2021-11-12 11:06 UTC, brunoramoa requested changes

2021-11-12 11:06 UTC, brunoramoa commented on doc/pages/meshParameters.md
> +\f$\vec{d}\f$ = Vector from Cell Owner Centre of Mass to Neighbour Cell Centre of Mass
They are still not correct...

2021-11-12 11:06 UTC, brunoramoa commented on doc/pages/meshParameters.md
> +\vec{n_f} =  \vec{S_f}/mag( \vec{S_f})
use latex fraction syntax

2021-11-12 11:06 UTC, brunoramoa commented on doc/pages/meshParameters.md
> +θ = a cos ( \frac{\ d.\vec{n_f}\ }{|d|.|n|} )
use latex syntax

2021-11-12 11:25 UTC, closed without merging