Group1 task3
Computational-Rheology/CRheoLab pull request #53
Opened 2022-04-11 16:59 UTC by ricardodpcosta

2022-04-19 12:43 UTC, brunoramoa requested changes

2022-04-19 12:43 UTC, brunoramoa commented on src/csrSpmat.cpp
> +  const Cell *neigh_ptr, *owner_ptr;
Suggestion: Change nz += 1, to nz++

2022-04-19 12:43 UTC, brunoramoa commented on src/csrSpmat.cpp
> +void csrSpmat::addValue(unsigned int &i, unsigned int &j, double &val)
Suggestion: pass the variables as a const ref since you are not changing the values inside the function

2022-04-19 12:43 UTC, brunoramoa commented on src/csrSpmat.cpp
> +double csrSpmat::getValue(unsigned int &i, unsigned int &j)
Suggestion: replace
```
 std::vector< std::vector<double> > denseMatrix(numRows_);
  std::vector<double> temp(numCols_);
  unsigned int id_column = 0;
  for(unsigned int i=0;i<numRows_;i++)
  {
    denseMatrix[i] = temp;
  }
```
with:
std::vector< std::vector<double> > denseMatrix(numCols_, std::vector<double>(numCols_));

2022-04-19 12:43 UTC, brunoramoa commented on src/csrSpmat.cpp
> +    if (i != columns_[j]) sumProdRow += values_[j] * vecPhi[columns_[j]];
Suggestion: Index the if statement:

`if (i != columns_[j]) sumProdRow += values_[j] * vecPhi[columns_[j]];`
by
```
if (i != columns_[j]) 
    sumProdRow += values_[j] * vecPhi[columns_[j]];
```

2022-04-20 14:19 UTC, ricardodpcosta commented on src/lilSpmat.cpp
> +double lilSpmat::vecMulNoDiagonal(const unsigned int &i, const std::vector<double> &vecPhi)
OK.

2022-04-20 14:20 UTC, ricardodpcosta commented on src/csrSpmat.cpp
> +  const Cell *neigh_ptr, *owner_ptr;
OK.

2022-04-20 14:23 UTC, ricardodpcosta commented on src/csrSpmat.cpp
> +void csrSpmat::addValue(unsigned int &i, unsigned int &j, double &val)
OK.

2022-04-20 14:25 UTC, ricardodpcosta commented on src/csrSpmat.cpp
> +    if (i != columns_[j]) sumProdRow += values_[j] * vecPhi[columns_[j]];
OK.

2022-04-20 14:28 UTC, ricardodpcosta commented on src/csrSpmat.cpp
> +  std::cout << "Error: invalid column for sparse structure matrix" << std::endl;
OK.

2022-04-20 14:29 UTC, closed without merging